[package]
name = "hydrogen"
version = "0.1.0"
authors = ["leigh_waller <leigh.waller2@icloud.com>"]

[dependencies]
log = "0.4.1"
env_logger = "0.5.6"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.6", features = ["serde", "v4"] }
toml = "0.4.*"
quick-error = "*"
